apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "act_runner.fullname" . }}
  labels:
    {{- include "act_runner.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "act_runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "act_runner.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "act_runner.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: act-runner
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sh", "-c", "while ! nc -z localhost 2376 </dev/null; do echo 'waiting for docker daemon...'; sleep 5; done; /sbin/tini -- /usr/local/bin/run.sh"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DOCKER_HOST
              value: "{{ .Values.act_runner.docker_host }}"
            {{- if not (hasPrefix "unix://" .Values.act_runner.docker_host) }}
            - name: DOCKER_CERT_PATH
              value: /certs/client
            - name: DOCKER_TLS_VERIFY
              value: "{{ .Values.act_runner.tls_verify }}"
            {{- end }}
            - name: GITEA_INSTANCE_URL
              value: {{ .Values.act_runner.instance }}
            - name: GITEA_RUNNER_MAX_PARALLEL_JOBS
              value: "{{ .Values.act_runner.parallel_jobs }}"
            - name: GITEA_RUNNER_LABELS
              value: {{ join "," .Values.act_runner.labels }}
            {{- with .Values.act_runner.env }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: GITEA_RUNNER_REGISTRATION_TOKEN
              valueFrom:
                secretKeyRef:
                  {{- if not .Values.act_runner.existingToken }}
                  name: {{ include "act_runner.fullname" . }}-secret
                  {{- else }}
                  name: {{ .Values.act_runner.existingToken }}
                  {{- end }}
                  key: act-runner-token
          volumeMounts:
            {{- if not (hasPrefix "unix://" .Values.act_runner.docker_host) }}
            - name: docker-certs
              mountPath: /certs
            {{- end }}
            - name: {{ include "act_runner.fullname" . }}-pvc
              mountPath: /data
            {{- with .Values.act_runner.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        - name: act-runner-dind
          securityContext:
            privileged: true
          image: "{{ .Values.imageDind.repository }}:{{ .Values.imageDind.tag }}"
          imagePullPolicy: {{ .Values.imageDind.pullPolicy }}
        {{- if .Values.imageDind.command }}
          command:
          {{- range .Values.imageDind.command }}
            - {{ . }}
          {{- end }}
        {{- end}}
          env:
            {{- if not (hasPrefix "unix://" .Values.act_runner.docker_host) }}
            - name: DOCKER_TLS_CERTDIR
              value: /certs
            {{- end }}
            {{- with .Values.act_runner.dindEnv }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            {{- if not (hasPrefix "unix://" .Values.act_runner.docker_host) }}
          - name: docker-certs
            mountPath: /certs
            {{- end }}
          - name: docker-graph-storage
            mountPath: /var/lib/docker
          {{- with .Values.act_runner.extraVolumeMounts }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
      volumes:
        {{- if not (hasPrefix "unix://" .Values.act_runner.docker_host) }}
        - name: docker-certs
          emptyDir: {}
        {{- end }}
        - name: docker-graph-storage
          emptyDir: {}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: {{ include "act_runner.fullname" . }}-pvc
          persistentVolumeClaim:
            claimName: {{ include "act_runner.fullname" . }}-pvc
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
